#!/bin/sh

usage()
{
 echo "This command initializes the HOTP counter on a HOTP security key to the specified value"
 echo "usage: $0 <hotpkey_admin_pin> <HOTP_secret> <HOTP_counter> <HOTP_key_branding>"
}

if [ "$4" == "" ]; then
  usage
  exit 1
fi

PIN=$1
SECRET=$2
COUNTER=$3
SECRET_B32=$(cat $SECRET | base32)
HOTPKEY_BRANDING=$4

hotp_verification set $SECRET_B32 "$PIN"
if [ $? -ne 0 ]; then
  echo "ERROR: Setting HOTP secret on $HOTPKEY_BRANDING failed!"
  exit 1
fi

i=9
while [ "$i" -lt "$COUNTER" ]; do
  echo "Updating counter to $i"
  HOTP_CODE=$(hotp $i < $SECRET)
  hotp_verification check $HOTP_CODE > /dev/null
  if [ $? -ne 0 ]; then
    echo "HOTP check failed for counter=$i, code=$HOTP_CODE"
    exit 1
  fi
  let "i += 10"
done

HOTP_CODE=$(hotp $COUNTER < $SECRET)
hotp_verification check $HOTP_CODE > /dev/null
if [ $? -ne 0 ]; then
  echo "HOTP check failed for counter=$COUNTER, code=$HOTP_CODE"
  exit 1
else
  echo "$HOTPKEY_BRANDING initialized at counter $COUNTER"
fi
