#!/bin/sh

usage()
{
 echo "This command initializes the Nitrokey HOTP counter to the specified value"
 echo "usage: $0 <nitrokey_admin_pin> <HOTP_secret> <HOTP_counter>"
}

if [ "$3" == "" ]; then
  usage
  exit 1
fi

PIN=$1
SECRET=$2
COUNTER=$3
SECRET_B32=$(cat $SECRET | base32)

nitrokey_hotp_verification set $SECRET_B32 "$PIN"
if [ $? -ne 0 ]; then
  echo "ERROR: Setting HOTP secret on Nitrokey failed!"
  exit 1
fi

i=9
while [ "$i" -lt "$COUNTER" ]; do
  echo "Updating counter to $i"
  HOTP_CODE=$(hotp $i < $SECRET)
  nitrokey_hotp_verification check $HOTP_CODE > /dev/null
  if [ $? -ne 0 ]; then
    echo "HOTP check failed for counter=$i, code=$HOTP_CODE"
    exit 1
  fi
  let "i += 10"
done

HOTP_CODE=$(hotp $i < $SECRET)
nitrokey_hotp_verification check $HOTP_CODE > /dev/null
if [ $? -ne 0 ]; then
  echo "HOTP check failed for counter=$COUNTER, code=$HOTP_CODE"
  exit 1
else
  echo "Nitrokey initialized at counter $COUNTER"
fi
